INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'pop');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'metal');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'dance');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'country');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'folk');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'R.n.B');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'soul');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'rap');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'regge');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'disco');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'hip hop');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'house');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'techno');
INSERT INTO public.zanr (zanr_id, popis) VALUES (default, 'rock');